import { QuickTourStep } from '../types';

export const QUICK_TOUR_STEPS: QuickTourStep[] = [
  {
    step: 1,
    title: 'SHIFT Key',
    description: 'If you press this key, the next key you press will perform its second function.\n\nThe key\'s second function is displayed in the label above.',
    targetKeyId: 'btn-shift',
  },
  {
    step: 2,
    title: 'MENU Button',
    description: 'Main calculator menu.\n\nYou can change the calculator mode, layout, theme, or adjust your calculator, including creating custom keyboard layouts.\n\nYou can also get help for all calculator functions or access the history or clipboard.',
    targetKeyId: 'btn-menu',
  },
  {
    step: 3,
    title: 'Expression Field',
    description: 'Here you can write the expression you want to evaluate.\n\nLong-press the expression to open the clipboard window.',
    targetKeyId: 'lcd-expression',
  },
  {
    step: 4,
    title: 'Calculation Result',
    description: 'See the result of your expression.\n\nTap it to change the result format or long-press it to open the clipboard window.',
    targetKeyId: 'lcd-result',
  },
  {
    step: 5,
    title: 'More Info',
    description: 'Press this button to get more information about calculation.\n\nYou\'ll have access to graphs, alternative result formats, function extremes, the complex plane, and more.',
    targetKeyId: 'btn-more',
  },
  {
    step: 6,
    title: 'Number Notation',
    description: 'Changes the number notation to scientific, engineering etc. Examples:\n\n• 1.23 × 10⁴\n• 12.3 × 10³\n• 12.3 k',
    targetKeyId: 'btn-fse',
  },
  {
    step: 7,
    title: 'Angle Mode',
    description: 'Changes the angle unit between degrees (DEG), radians (RAD) and gradians (GRAD).',
    targetKeyId: 'btn-drg',
  },
  {
    step: 8,
    title: 'Matrix Operations',
    description: 'Inserts a matrix into the expression.\n\nPress the [ MTRX ] key to see matrix operations.',
    targetKeyId: 'btn-mtrx',
  },
  {
    step: 9,
    title: 'Camera Solver',
    description: 'Take a picture of a mathematical expression and let the calculator recognize the content.\n\nYou can also select an image from the gallery.',
    targetKeyId: 'btn-cam',
  },
  {
    step: 10,
    title: 'Polar Form',
    description: 'When complex numbers are turned on, press to insert numbers in polar form.',
    targetKeyId: 'btn-i',
  },
  {
    step: 11,
    title: 'Imaginary Unit',
    description: 'When complex numbers are turned on, press to insert the imaginary unit into the expression.',
    targetKeyId: 'btn-i',
  },
  {
    step: 12,
    title: 'Statistics',
    description: 'Menu with all statistical functions including regression.\n\nUse a matrix with one or two rows as a parameter, where the first row represents the data set. The second row is optional and may contain absolute or relative frequencies of the data.',
    targetKeyId: 'btn-recip',
  },
  {
    step: 13,
    title: 'Sexagesimal Angles',
    description: 'Use to insert the number in sexagesimal form, i.e. degrees, minutes and seconds.\n\nNote that trigonometric functions operate based on the angular unit selected by the [ DRG ] key and are not influenced by whether the number is entered in sexagesimal form.',
    targetKeyId: 'btn-dms',
  },
  {
    step: 14,
    title: 'Variables',
    description: 'Inserts the variable "x" into the expression. Similarly, you can enter the variable "y".\n\nYou can create more variables and use them if you press the [ XY,M ] key.',
    targetKeyId: 'btn-varx',
  },
  {
    step: 15,
    title: 'Variable & Memory Manager',
    description: 'Press to create or update your own variables, functions and memories. Insert them into the expression.',
    targetKeyId: 'btn-xym',
  },
  {
    step: 16,
    title: 'History Access',
    description: 'Access your previous calculations and their results.',
    targetKeyId: 'btn-xym',
  },
  {
    step: 17,
    title: 'Complex Numbers Menu',
    description: 'Menu with functions for complex numbers.',
    targetKeyId: 'btn-7',
  },
  {
    step: 18,
    title: 'Repeating Digits',
    description: 'Allows you to enter repeating digits in a decimal number.\n\nPress the key to start entering the repeating part, or press it within the decimal part of the number to set where the repeating part starts.\n\nPress the key again at the start of the repeating part to cancel it.',
    targetKeyId: 'btn-9',
  },
  {
    step: 19,
    title: 'Constants',
    description: 'More than 200 physical and mathematical constants.\n\nYou can create a list of your favorite constants.',
    targetKeyId: 'btn-1',
  },
  {
    step: 20,
    title: 'Unit Converter',
    description: 'Conversion between various physical units.\n\nYou can create a list of your favorite units.',
    targetKeyId: 'btn-2',
  },
  {
    step: 21,
    title: 'Other Functions',
    description: 'All functions that don\'t have dedicated keys can be found here.',
    targetKeyId: 'btn-0',
  },
  {
    step: 22,
    title: 'Exponent',
    description: 'Add the exponent to the number on the display.',
    targetKeyId: 'btn-exp',
  },
  {
    step: 23,
    title: 'SI Unit Exponent',
    description: 'Add the exponent to the number as a SI unit prefix, e.g. kilo, mega, giga etc.',
    targetKeyId: 'btn-exp',
  },
  {
    step: 24,
    title: 'Relational Operators',
    description: 'Choose relational operator (e.g. =, < etc.) if you want to evaluate equations or inequalities.',
    targetKeyId: 'btn-eq',
  },
  {
    step: 25,
    title: 'Finish Calculation',
    description: 'Press the key to finish the calculation. It means:\n\n• Highlight the position of error in expression,\n• The result will be accessible using the [ Ans ] key,\n• Close all unclosed parentheses,\n• Evaluate expression if immediate evaluation is turned off.',
    targetKeyId: 'btn-eq',
  },
];
